### ISSUE TITLE
Chapter 13: Investigate the possibility of using private Docker image on ghcr.io

### ISSUE THREAD

**Issue by leonardcser** [csia-pme/a-guide-to-mlops#117]
This is possible by overriding the `resources.yaml.j2` template with the flag `templates_dir.0`.

https://dev.to/asizikov/using-github-container-registry-with-kubernetes-38fb

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: {{ namespace }}
  labels:
    name: {{ namespace }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ image_name }}
  namespace: {{ namespace }}
spec:
  selector:
    matchLabels:
      app: {{ image_name }}
  template:
    metadata:
      labels:
        app: {{ image_name }}
    spec:
      containers:
      - name: {{ image_name }}
        image: {{ image_uri }}
        imagePullPolicy: {{ image_pull_policy }}
        ports:
        - containerPort: {{ port }}
      imagePullSecrets:
      - name: dockerconfigjson-github-com

---

apiVersion: v1
kind: Service
metadata:
  name: {{ image_name }}
  namespace: {{ namespace }}
  labels:
    run: {{ image_name }}
spec:
  ports:
  - port: {{ port }}
    protocol: TCP
    targetPort: {{ port }}
  selector:
    app: {{ image_name }}
  type: {{ service_type }}

---

kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: dockerconfigjson-github-com
  namespace: {{ namespace }}
  labels:
    app: dockerconfigjson-github-com
data:
  .dockerconfigjson: <SECRET HERE>
```
