### ISSUE TITLE
Chapters 8-9: Add pip cache to CI/CD

### ISSUE THREAD

**Issue by leonardcser** [csia-pme/a-guide-to-mlops#120]
Update the Setup Python Action to the following in order to cache pip dependencies

```yaml
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
```

```diff
       - name: Setup Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
+          cache: 'pip'
```
