### ISSUE TITLE
Deploy MinIO : The request signature we calculated does not match the signature you provided. Check your key and signing method.

### ISSUE THREAD

**Issue by robinfru** [csia-pme/a-guide-to-mlops#62]
Hi everyone,

I would like to deploy MinIO like as you explain in the guide, but I have some problems.

What I do :
1. Clone the repo
2. Go to infrastructure/minio
3. Create the folder minio-data
4. Start the container with `docker compose up --detach`

With my browser, I can go to localhost:9001 and the login page appears. When I set the default login (user: minio, password: minio123), the web page tells me : The request signature we calculated does not match the signature you provided. Check your key and signing method.

Is it the wrong password and username ?

I tried modifying the docker-compose as below and it works with the username and the password minio, minio123 :
```yaml
networks:
  minio:
    name: minio

services:
  minio:
    container_name: minio
    image: quay.io/minio/minio
    restart: unless-stopped
    env_file:
      - minio.env
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    networks:
      - minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./minio-data:/data:rw
```

Can you tell me what's going on ?

Thank you and have a nice day.
